name: hjsphoto
favicon: null
layout_spectrum: 0.26188
typography_spectrum: 0.16961
title: Site Title
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0043ae'
    - '#9e001b'
    - '#8fb048'
    - '#527416'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
